pub const STOCKPILE_ZIP_SCHEMA_VERSION: u32 = 2;
pub const STOCKPILE_MATERIALS_SCHEMA_VERSION: u32 = 2;
pub const STOCKPILE_RECIPE_TREES_SCHEMA_VERSION: u32 = 2;
pub const STOCKPILE_I18N_SCHEMA_VERSION: u32 = 1;
pub const STOCKPILE_ICONS_SCHEMA_VERSION: u32 = 1;
pub const STOCKPILE_ITEM_NAMES_SCHEMA_VERSION: u32 = 1;
pub const STOCKPILE_SQLITE_SCHEMA_VERSION: u32 = 4;
pub const STOCKPILE_SESSION_EXPORT_SCHEMA_VERSION: u32 = 1;
