import React, { useEffect, useMemo, useState } from "react";
import { BlockSearchSelect } from "../../../../components/BlockSearchSelect";
import { Dropdown } from "../../../../components/Dropdown";
import {
  getAllBlocks,
  getBlockProperties,
  getDefaultProperties,
  loadDatabases,
  translateKey,
  translateValue,
} from "../../../../../src/business/facade";
import {
  getDefaultProjectionOutputPath,
  openExternalPath,
  openProjectionViewer,
  selectJsonSavePath,
  selectLitematicSavePath,
  writeWorkspaceFile,
} from "../../../../../src/business/facade";
import { addOrUpdateRecord, loadLibrary } from "../../../../../src/business/facade";
import {
  GenerationTemplate,
  exportTemplate,
  loadGenerationTemplates,
  templateToForm,
} from "../../../../../src/business/facade";
import {
  OperationFormState,
  OperationType,
  GenerateFormState,
  GenerateSummary,
  MaterialEntrySpec,
  MaterialSpec,
  applyGenerate,
  buildProjectionPlan,
  createDefaultOperation,
  dryRunGenerate,
  ensureLitematicExtension,
  formatGeneratePathLog,
  sanitizeFileName,
  validateOutputPath,
  validatePlanClientSide,
} from "../../../../../src/business/facade";
import {
  AiPlanMessage,
  aiGeneratePlan,
  applyAiPlanToGenerateForm,
  buildWrappedPrompt,
  buildWebPrompt,
  extractPlanFromAiText,
  getAiPlanWarnings,
  normalizeAiPlanForImport,
  sendAiChatMessage,
  validateAiPlanBasic,
} from "../../../../../src/business/facade";

type Status = "未生成" | "Dry-run 完成" | "正在生成" | "已生成" | "失败";

const operationLabels: Array<{ label: string; value: OperationType }> = [
  { label: "实心长方体", value: "fill_box" },
  { label: "空心长方体", value: "hollow_box" },
  { label: "地板", value: "floor" },
  { label: "墙体", value: "wall" },
  { label: "柱子", value: "pillar" },
  { label: "圆柱", value: "cylinder" },
  { label: "球体", value: "sphere" },
  { label: "边框盒", value: "outline_box" },
  { label: "棋盘地板", value: "checkerboard_floor" },
  { label: "双坡屋顶", value: "roof_gable" },
  { label: "圆环", value: "ring" },
];

function makeId(): string {
  return `${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function cloneBlock(block: { name: string; properties?: Record<string, string> }) {
  return { name: block.name, properties: { ...(block.properties || {}) } };
}

function cloneMaterial(material: MaterialSpec | undefined): MaterialSpec | undefined {
  if (!material) return undefined;
  if (material.type === "single") return { type: "single", block: cloneBlock(material.block) };
  return {
    type: "weighted_random",
    seed: material.seed,
    entries: material.entries.map((entry) => ({
      id: makeId(),
      weight: entry.weight,
      block: cloneBlock(entry.block),
    })),
  };
}

function defaultFormState(): GenerateFormState {
  return {
    metadata: {
      name: "Generated Projection",
      author: "Litematica-BA",
      description: "Generated by Litematica-BA",
      minecraftDataVersion: 3953,
    },
    region: {
      name: "main",
      origin: [0, 0, 0],
      size: [32, 16, 32],
    },
    operations: [
      { ...createDefaultOperation("floor"), from: [0, 0, 0], to: [31, 0, 31] },
      createDefaultOperation("hollow_box"),
    ],
  };
}

export function GeneratePage({ currentFile, setCurrentFile, setRoute }: any) {
  const [form, setForm] = useState<GenerateFormState>(() => defaultFormState());
  const [status, setStatus] = useState<Status>("未生成");
  const [clientErrors, setClientErrors] = useState<string[]>([]);
  const [dryRunSummary, setDryRunSummary] = useState<GenerateSummary | null>(null);
  const [rawOutput, setRawOutput] = useState("");
  const [lastError, setLastError] = useState("");
  const [outputPath, setOutputPath] = useState("");
  const [generatedPath, setGeneratedPath] = useState("");
  const [detailsOpen, setDetailsOpen] = useState(true);
  const [rawOpen, setRawOpen] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [aiPlanText, setAiPlanText] = useState("");
  const [aiImportedPlan, setAiImportedPlan] = useState<any | null>(null);
  const [aiPlanErrors, setAiPlanErrors] = useState<string[]>([]);
  const [aiPlanWarnings, setAiPlanWarnings] = useState<string[]>([]);
  const [aiWebPromptCopied, setAiWebPromptCopied] = useState(false);
  const [aiChatOpen, setAiChatOpen] = useState(false);
  const [aiDirectMode, setAiDirectMode] = useState(false);
  const [aiChatMessages, setAiChatMessages] = useState<AiPlanMessage[]>([]);
  const [aiChatInput, setAiChatInput] = useState("");
  const [aiChatSending, setAiChatSending] = useState(false);
  const [aiChatError, setAiChatError] = useState("");
  const [aiChatPlan, setAiChatPlan] = useState<any | null>(null);
  const [allBlocks, setAllBlocks] = useState<string[]>(() => getAllBlocks().sort());
  const [templates, setTemplates] = useState<GenerationTemplate[]>([]);
  const [templateQuery, setTemplateQuery] = useState("");
  const [templateTag, setTemplateTag] = useState("");
  const [formDirty, setFormDirty] = useState(false);

  const plan = useMemo(() => buildProjectionPlan(form), [form]);
  const planJson = useMemo(() => JSON.stringify(plan, null, 2), [plan]);
  const currentValidation = useMemo(() => validatePlanClientSide(plan), [plan]);

  useEffect(() => {
    let active = true;
    loadDatabases().then(() => {
      if (active) setAllBlocks(getAllBlocks().sort());
    });
    loadGenerationTemplates()
      .then((items) => {
        if (active) setTemplates(items);
      })
      .catch((error) => console.warn("failed to load generation templates", error));
    return () => {
      active = false;
    };
  }, []);

  const templateTags = useMemo(() => Array.from(new Set(templates.flatMap((template) => template.tags || []))).sort((a, b) => a.localeCompare(b, "zh-CN")), [templates]);
  const filteredTemplates = useMemo(() => {
    const needle = templateQuery.trim().toLowerCase();
    return templates.filter((template) => {
      const tagOk = !templateTag || template.tags.includes(templateTag);
      const haystack = `${template.id} ${template.name_zh} ${template.description_zh} ${(template.tags || []).join(" ")}`.toLowerCase();
      return tagOk && (!needle || haystack.includes(needle));
    });
  }, [templates, templateQuery, templateTag]);

  const clearDryRun = () => {
    setDryRunSummary(null);
    setRawOutput("");
    setLastError("");
    if (status !== "未生成") setStatus("未生成");
  };

  const updateMetadata = (key: keyof GenerateFormState["metadata"], value: string | number) => {
    setForm((prev) => ({ ...prev, metadata: { ...prev.metadata, [key]: value } }));
    setFormDirty(true);
    clearDryRun();
  };

  const updateRegion = (key: keyof GenerateFormState["region"], value: string | [number, number, number]) => {
    setForm((prev) => ({ ...prev, region: { ...prev.region, [key]: value } }));
    setFormDirty(true);
    clearDryRun();
  };

  const updateOperation = (index: number, operation: OperationFormState) => {
    setForm((prev) => {
      const operations = [...prev.operations];
      operations[index] = operation;
      return { ...prev, operations };
    });
    setFormDirty(true);
    clearDryRun();
  };

  const handleLoadTemplate = (template: GenerationTemplate) => {
    if (formDirty && !window.confirm("当前方案已有修改，确定用模板覆盖当前表单吗？")) return;
    setForm(templateToForm(template));
    setFormDirty(false);
    setGeneratedPath("");
    clearDryRun();
  };

  const handleExportTemplate = async () => {
    const selected = await selectJsonSavePath(`${sanitizeFileName(form.metadata.name || "custom_template")}.json`);
    if (selected) await exportTemplate(selected, form, plan);
  };

  const handleDryRun = async () => {
    const errors = validatePlanClientSide(plan);
    setClientErrors(errors);
    setLastError("");
    if (errors.length) {
      setStatus("失败");
      return;
    }
    try {
      const result = await dryRunGenerate(plan);
      setDryRunSummary(result.summary);
      setRawOutput(`${result.pathLog}\n\n${result.rawOutput}`);
      setOutputPath(outputPath || await getDefaultProjectionOutputPath(currentFile, form.metadata.name));
      setStatus("Dry-run 完成");
    } catch (error: any) {
      setLastError(error.toString());
      setStatus("失败");
    }
  };

  const chooseOutput = async () => {
    const defaultPath = outputPath || await getDefaultProjectionOutputPath(currentFile, form.metadata.name);
    const selected = await selectLitematicSavePath(defaultPath);
    if (selected) setOutputPath(ensureLitematicExtension(selected));
  };

  const handleApply = async () => {
    const errors = validatePlanClientSide(plan);
    setClientErrors(errors);
    setLastError("");
    if (errors.length) {
      setStatus("失败");
      return;
    }
    if (!dryRunSummary) {
      setLastError("请先完成 Dry-run 预览。");
      return;
    }
    if (!outputPath) {
      await chooseOutput();
      return;
    }

    const outputValidation = await validateOutputPath(outputPath);
    const preflightLog = formatGeneratePathLog({
      selected_output_raw: outputPath,
      normalized_output: outputValidation.normalizedPath,
      parent_dir: outputValidation.parentDir,
      parent_exists: outputValidation.parentExists,
      output_has_litematic_ext: outputValidation.outputHasLitematicExt,
      output_is_absolute: outputValidation.outputIsAbsolute,
      command_args: ["generate", "--plan", "<temp_plan.json>", "--output", outputValidation.normalizedPath],
    });
    console.log(preflightLog);
    setRawOutput(preflightLog);
    if (!outputValidation.ok) {
      setLastError(outputValidation.error || "输出路径无效。");
      return;
    }
    setOutputPath(outputValidation.normalizedPath);

    setStatus("正在生成");
    try {
      const result = await applyGenerate(plan, outputValidation.normalizedPath);
      setDryRunSummary(result.summary);
      setRawOutput(`${result.pathLog}\n\n${result.rawOutput}\n\n[analyze]\n${result.analyzeOutput || ""}`);
      const finalPath = result.normalizedOutputPath || outputValidation.normalizedPath;
      const library = await loadLibrary();
      await addOrUpdateRecord(library, finalPath);
      setCurrentFile(finalPath);
      setGeneratedPath(finalPath);
      setStatus("已生成");
    } catch (error: any) {
      setLastError(error.toString());
      setStatus("失败");
    }
  };

  const savePlan = async () => {
    const selected = await selectJsonSavePath("projection_plan.json");
    if (selected) await writeWorkspaceFile(selected, planJson);
  };

  const openFolder = async () => {
    if (!generatedPath) return;
    const index = Math.max(generatedPath.lastIndexOf("\\"), generatedPath.lastIndexOf("/"));
    if (index > 0) await openExternalPath(generatedPath.slice(0, index));
  };

  const previewImportedPlan = (text: string) => {
    const importedPlan = extractPlanFromAiText(text);
    const normalized = normalizeAiPlanForImport(importedPlan);
    const errors = [...validateAiPlanBasic(normalized.plan), ...normalized.errors];
    const warnings = [...normalized.warnings, ...getAiPlanWarnings(normalized.plan)];
    setAiImportedPlan(errors.length ? null : normalized.plan);
    setAiPlanErrors(errors);
    setAiPlanWarnings(warnings);
    setAiPlanText(JSON.stringify(normalized.plan, null, 2));
    return { importedPlan: normalized.plan, errors, warnings };
  };

  const applyMockPlan = async () => {
    const generated = await aiGeneratePlan({
      provider: "mock",
      prompt: aiPrompt,
      currentPlan: plan,
      context: {
        defaultSize: form.region.size,
        minecraftDataVersion: form.metadata.minecraftDataVersion,
      },
    });
    const text = JSON.stringify(generated, null, 2);
    setAiPlanText(text);
    previewImportedPlan(text);
  };

  const copyWebPrompt = async () => {
    const fullPrompt = await buildWebPrompt(aiPrompt, plan);
    await navigator.clipboard.writeText(fullPrompt);
    setAiWebPromptCopied(true);
    window.setTimeout(() => setAiWebPromptCopied(false), 1600);
  };

  const importAiPlan = () => {
    try {
      previewImportedPlan(aiPlanText);
    } catch (error: any) {
      setAiImportedPlan(null);
      setAiPlanWarnings([]);
      setAiPlanErrors([`JSON parse failed: ${error.message || error}`]);
    }
  };

  const applyImportedPlan = (importedPlan: any) => {
    const normalized = normalizeAiPlanForImport(importedPlan);
    const errors = [...validateAiPlanBasic(normalized.plan), ...normalized.errors];
    setAiPlanErrors(errors);
    setAiPlanWarnings([...normalized.warnings, ...getAiPlanWarnings(normalized.plan)]);
    if (errors.length) return;
    if (formDirty && !window.confirm("当前方案已有修改，确定用 AI plan 覆盖当前表单吗？")) return;
    setForm(applyAiPlanToGenerateForm(normalized.plan));
    setAiImportedPlan(normalized.plan);
    setAiPlanText(JSON.stringify(normalized.plan, null, 2));
    setFormDirty(true);
    setGeneratedPath("");
    clearDryRun();
  };

  const handleAiChatSend = async () => {
    const userText = aiChatInput.trim();
    if (!userText || aiChatSending) return;
    setAiChatSending(true);
    setAiChatError("");
    try {
      const content = aiDirectMode ? userText : await buildWrappedPrompt(userText, plan);
      const userMessage: AiPlanMessage = {
        role: "user",
        content,
        timestamp: Date.now(),
        planSnapshot: aiDirectMode ? undefined : plan,
      };
      const nextMessages = [...aiChatMessages, userMessage];
      setAiChatMessages(nextMessages);
      setAiChatInput("");

      const assistantMessage = await sendAiChatMessage({ messages: nextMessages });
      const finalMessages = [...nextMessages, assistantMessage];
      setAiChatMessages(finalMessages);

      try {
        const extracted = extractPlanFromAiText(assistantMessage.content);
        const normalized = normalizeAiPlanForImport(extracted);
        const errors = [...validateAiPlanBasic(normalized.plan), ...normalized.errors];
        const warnings = [...normalized.warnings, ...getAiPlanWarnings(normalized.plan)];
        setAiPlanErrors(errors);
        setAiPlanWarnings(warnings);
        setAiChatPlan(errors.length ? null : normalized.plan);
        setAiImportedPlan(errors.length ? null : normalized.plan);
        setAiPlanText(JSON.stringify(normalized.plan, null, 2));
        if (!errors.length) {
          applyImportedPlan(normalized.plan);
        }
      } catch (parseError: any) {
        setAiChatPlan(null);
        setAiImportedPlan(null);
        setAiPlanErrors([`AI response parse failed: ${parseError.message || parseError}`]);
        setAiPlanWarnings([]);
      }
    } catch (error: any) {
      setAiChatError(String(error?.message || error));
    } finally {
      setAiChatSending(false);
    }
  };

  const clearAiChat = () => {
    setAiChatMessages([]);
    setAiChatInput("");
    setAiChatError("");
    setAiChatPlan(null);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", gap: 12 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
        <div>
          <div style={{ fontSize: "1.3em", fontWeight: "bold" }}>投影生成</div>
          <div style={{ opacity: 0.7, fontSize: "0.9em" }}>通过本地参数化 plan 生成 .litematic，后续可接入智能生成。</div>
        </div>
        <div style={{ flex: 1 }} />
        <div className="form-field" style={{ flex: "0 0 auto" }}>
          <span>当前状态：</span>
          <strong>{status}</strong>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "minmax(620px, 1.15fr) minmax(420px, 0.85fr)", gap: 12, minHeight: 0, flex: 1 }}>
        <div style={{ overflowY: "auto", paddingRight: 4 }}>
          <MetadataGroup form={form} updateMetadata={updateMetadata} />
          <RegionGroup form={form} updateRegion={updateRegion} />
          <TemplateLibrary
            templates={filteredTemplates}
            allTags={templateTags}
            query={templateQuery}
            selectedTag={templateTag}
            onQueryChange={setTemplateQuery}
            onTagChange={setTemplateTag}
            onLoad={handleLoadTemplate}
            onExportCurrent={handleExportTemplate}
          />

          <div className="group-box">
            <div className="group-box-title">操作列表</div>
            <div style={{ display: "flex", gap: 8, marginBottom: 10 }}>
              <button className="btn" onClick={() => { setForm((prev) => ({ ...prev, operations: [...prev.operations, createDefaultOperation("fill_box")] })); setFormDirty(true); clearDryRun(); }}>添加操作</button>
              <button className="btn" onClick={() => { setForm((prev) => ({ ...prev, operations: [] })); setFormDirty(true); clearDryRun(); }}>清空</button>
              <div style={{ flex: 1 }} />
              <span style={{ opacity: 0.65 }}>后面的 operation 会覆盖前面的方块。</span>
            </div>
            {form.operations.map((operation, index) => (
              <OperationEditor
                key={operation.id}
                operation={operation}
                index={index}
                allBlocks={allBlocks}
                onChange={(next) => updateOperation(index, next)}
                onRemove={() => {
                  setForm((prev) => ({ ...prev, operations: prev.operations.filter((_, i) => i !== index) }));
                  clearDryRun();
                }}
                onDuplicate={() => {
                  setForm((prev) => {
                    const copy = {
                      ...operation,
                      id: makeId(),
                      block: cloneBlock(operation.block),
                      material: cloneMaterial(operation.material),
                    };
                    const operations = [...prev.operations];
                    operations.splice(index + 1, 0, copy);
                    return { ...prev, operations };
                  });
                  clearDryRun();
                }}
              />
            ))}
          </div>

          <div className="group-box">
            <div className="group-box-title">智能生成（网页端）</div>
            <div className="form-row">
              <div className="form-label">自然语言需求</div>
              <textarea className="input" value={aiPrompt} onChange={(e) => setAiPrompt(e.target.value)} placeholder="描述要生成或修改的投影；本区域不会自动调用真实 API。" style={{ flex: 1, minHeight: 60, resize: "vertical" }} />
            </div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 8 }}>
              <button className="btn" onClick={copyWebPrompt}>复制给网页端 AI 的完整提示词</button>
              <button className="btn" onClick={applyMockPlan}>Mock 生成示例方案</button>
              <button className="btn" onClick={() => setAiChatOpen((open) => !open)}>使用 API 对话</button>
              {aiWebPromptCopied && <span style={{ opacity: 0.75 }}>已复制</span>}
            </div>
            <div className="form-row">
              <div className="form-label">导入 AI 输出</div>
              <textarea
                className="input"
                value={aiPlanText}
                onChange={(e) => {
                  setAiPlanText(e.target.value);
                  setAiImportedPlan(null);
                  setAiPlanErrors([]);
                  setAiPlanWarnings([]);
                }}
                placeholder="粘贴 AI 返回的 projection_plan.json。不会自动生成 .litematic。"
                style={{ flex: 1, minHeight: 90, resize: "vertical", fontFamily: "Consolas, monospace" }}
              />
            </div>
            <div style={{ display: "flex", gap: 8, marginBottom: 8, flexWrap: "wrap" }}>
              <button className="btn" onClick={importAiPlan}>解析并预览</button>
              <button className="btn" onClick={() => aiImportedPlan && applyImportedPlan(aiImportedPlan)} disabled={!aiImportedPlan}>应用到当前方案</button>
            </div>
            {aiPlanErrors.length > 0 && <ErrorList errors={aiPlanErrors} />}
            {aiPlanWarnings.length > 0 && (
              <div style={{ color: "#ffd580", marginBottom: 8 }}>
                {aiPlanWarnings.map((warning) => <div key={warning}>warning: {warning}</div>)}
              </div>
            )}
            {aiImportedPlan && (
              <details open style={{ marginBottom: 8 }}>
                <summary style={{ cursor: "pointer" }}>AI plan 预览</summary>
                <pre className="generate-json-preview" style={{ maxHeight: 220 }}>{JSON.stringify(aiImportedPlan, null, 2)}</pre>
              </details>
            )}
            <div style={{ opacity: 0.7, fontSize: "0.9em" }}>
              AI 只生成 projection_plan.json；导入后仍需用户确认应用，并手动 Dry-run / Apply。复制内容包含 prompt_config、当前 region/plan 和用户需求，不包含 API Key 或本地文件路径。
            </div>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", minHeight: 0, gap: 12 }}>
          <div className="group-box" style={{ flex: "1 1 45%", minHeight: 0, display: "flex", flexDirection: "column" }}>
            <div className="group-box-title">projection_plan.json 预览</div>
            <div style={{ display: "flex", gap: 8, marginBottom: 8 }}>
              <button className="btn" onClick={() => setDetailsOpen(!detailsOpen)}>{detailsOpen ? "折叠" : "展开"}</button>
              <button className="btn" onClick={() => navigator.clipboard.writeText(planJson)}>复制 plan JSON</button>
              <button className="btn" onClick={savePlan}>保存 plan...</button>
            </div>
            {detailsOpen && <pre className="generate-json-preview">{planJson}</pre>}
          </div>

          <div className="group-box">
            <div className="group-box-title">生成</div>
            {currentValidation.length > 0 && <ErrorList errors={currentValidation} />}
            {clientErrors.length > 0 && <ErrorList errors={clientErrors} />}
            <div style={{ display: "flex", gap: 8, marginBottom: 8 }}>
              <button className="btn" onClick={handleDryRun}>Dry-run 预览</button>
              <button className="btn" onClick={chooseOutput}>选择输出路径...</button>
              <button className="btn" onClick={handleApply} disabled={!dryRunSummary || status === "正在生成"}>生成 .litematic</button>
            </div>
            <div className="form-row">
              <div className="form-label">输出路径</div>
              <input className="input" style={{ flex: 1 }} value={outputPath} onChange={(e) => setOutputPath(e.target.value)} placeholder="完整绝对路径，例如 C:\path\name.litematic" />
            </div>
            {lastError && <textarea readOnly className="input" value={lastError} style={{ width: "100%", height: 84, color: "#ffb0b0", resize: "vertical" }} />}
            {dryRunSummary && <SummaryView summary={dryRunSummary} />}
            {rawOutput && (
              <div style={{ marginTop: 8 }}>
                <button className="btn" onClick={() => setRawOpen(!rawOpen)}>{rawOpen ? "隐藏 raw output" : "显示 raw output"}</button>
                {rawOpen && <textarea readOnly className="input" value={rawOutput} style={{ width: "100%", height: 160, marginTop: 8, resize: "vertical", fontFamily: "monospace" }} />}
              </div>
            )}
            {generatedPath && (
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
                <button className="btn" onClick={() => setRoute("properties")}>打开属性页</button>
                <button className="btn" onClick={() => setRoute("library")}>打开投影库</button>
                <button className="btn" onClick={() => setRoute("render")}>打开 3D 预览页</button>
                <button className="btn" onClick={() => openProjectionViewer(generatedPath, "full")}>直接打开 3D 预览</button>
                <button className="btn" onClick={openFolder}>打开所在文件夹</button>
              </div>
            )}
          </div>
        </div>
      </div>
      {aiChatOpen && (
        <div style={{ position: "fixed", inset: 0, zIndex: 1000, background: "rgba(0,0,0,0.58)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24 }}>
          <div className="group-box" style={{ width: "min(920px, 96vw)", height: "min(760px, 92vh)", display: "flex", flexDirection: "column", gap: 10 }}>
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              <div className="group-box-title" style={{ margin: 0 }}>API 智能生成</div>
              <div style={{ flex: 1 }} />
              <button className="btn" onClick={() => setAiDirectMode((value) => !value)}>
                更改：{aiDirectMode ? "开启 = 直接发送原文" : "关闭 = 使用生成配置包装"}
              </button>
              <button className="btn" onClick={clearAiChat}>清空对话</button>
              <button className="btn" onClick={() => setAiChatOpen(false)}>关闭</button>
            </div>
            <div style={{ flex: 1, overflowY: "auto", background: "#111", border: "1px solid #333", padding: 8 }}>
              {aiChatMessages.length === 0 ? (
                <div style={{ opacity: 0.65 }}>暂无消息。默认发送 prompt_config + 当前上下文 + 用户输入；开启“更改”后只发送原文。</div>
              ) : (
                aiChatMessages.map((message, index) => (
                  <div key={`${message.role}-${message.timestamp || index}`} style={{ marginBottom: 10 }}>
                    <div style={{ opacity: 0.75, fontWeight: "bold" }}>{message.role === "assistant" ? "AI" : message.role === "system" ? "System" : "User"}</div>
                    <pre style={{ whiteSpace: "pre-wrap", margin: 0, fontFamily: "Consolas, monospace" }}>
                      {message.content.length > 5000 ? `${message.content.slice(0, 5000)}\n...` : message.content}
                    </pre>
                  </div>
                ))
              )}
            </div>
            <textarea
              className="input"
              value={aiChatInput}
              onChange={(event) => setAiChatInput(event.target.value)}
              placeholder={aiDirectMode ? "直接发送给 API 的原文" : "输入自然语言需求；发送时会包装生成配置和当前 plan"}
              style={{ minHeight: 86, resize: "vertical" }}
            />
            <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>
              <button className="btn" onClick={handleAiChatSend} disabled={aiChatSending || !aiChatInput.trim()}>
                {aiChatSending ? "发送中..." : "发送"}
              </button>
              <button className="btn" onClick={() => aiChatPlan && applyImportedPlan(aiChatPlan)} disabled={!aiChatPlan}>应用 AI 返回的 plan</button>
              <span style={{ opacity: 0.7 }}>{aiDirectMode ? "当前：直接发送原文" : "当前：使用生成配置包装"}</span>
            </div>
            {aiChatError && <div style={{ color: "#ff8888", whiteSpace: "pre-wrap" }}>{aiChatError}</div>}
          </div>
        </div>
      )}
    </div>
  );
}

function TemplateLibrary({
  templates,
  allTags,
  query,
  selectedTag,
  onQueryChange,
  onTagChange,
  onLoad,
  onExportCurrent,
}: {
  templates: GenerationTemplate[];
  allTags: string[];
  query: string;
  selectedTag: string;
  onQueryChange: (value: string) => void;
  onTagChange: (value: string) => void;
  onLoad: (template: GenerationTemplate) => void;
  onExportCurrent: () => void;
}) {
  return (
    <div className="group-box">
      <div className="group-box-title">模板库</div>
      <div style={{ display: "flex", gap: 8, marginBottom: 8, alignItems: "center" }}>
        <input className="input" value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="搜索模板名称 / 标签 / id" style={{ flex: 1 }} />
        <select className="input" value={selectedTag} onChange={(event) => onTagChange(event.target.value)}>
          <option value="">全部标签</option>
          {allTags.map((tag) => <option key={tag} value={tag}>{tag}</option>)}
        </select>
        <button className="btn" onClick={onExportCurrent}>保存当前方案为模板...</button>
      </div>
      <div className="template-library-list">
        {templates.map((template) => (
          <div key={template.id} className="template-library-row">
            <div style={{ minWidth: 0, flex: 1 }}>
              <div style={{ fontWeight: "bold" }}>{template.name_zh}</div>
              <div style={{ opacity: 0.72, fontSize: "0.9em" }}>{template.description_zh}</div>
              <div style={{ opacity: 0.62, fontSize: "0.85em" }}>{template.tags.join(" / ")}</div>
            </div>
            <button className="btn" onClick={() => onLoad(template)}>复制为当前方案</button>
          </div>
        ))}
        {templates.length === 0 && <div style={{ opacity: 0.65, padding: 8 }}>没有匹配模板</div>}
      </div>
    </div>
  );
}

function OperationEditor({ operation, index, allBlocks, onChange, onRemove, onDuplicate }: {
  operation: OperationFormState;
  index: number;
  allBlocks: string[];
  onChange: (operation: OperationFormState) => void;
  onRemove: () => void;
  onDuplicate: () => void;
}) {
  const update = (patch: Partial<OperationFormState>) => onChange({ ...operation, ...patch });
  return (
    <div className="generate-operation">
      <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}>
        <strong>#{index + 1}</strong>
        <Dropdown value={operation.type} options={operationLabels} onChange={(value) => update({ type: value as OperationType })} />
        <div style={{ flex: 1 }} />
        <button className="btn" onClick={onDuplicate}>复制</button>
        <button className="btn" onClick={onRemove}>删除</button>
      </div>

      {["fill_box", "hollow_box", "floor", "wall", "outline_box", "checkerboard_floor", "roof_gable"].includes(operation.type) && (
        <>
          <Vec3Row label="from x/y/z" value={operation.from} onChange={(value) => update({ from: value })} />
          <Vec3Row label="to x/y/z" value={operation.to} onChange={(value) => update({ to: value })} />
        </>
      )}
      {["hollow_box", "wall"].includes(operation.type) && <NumberRow label="thickness" value={operation.thickness} min={1} onChange={(value) => update({ thickness: value })} />}
      {operation.type === "pillar" && (
        <>
          <Vec3Row label="base x/y/z" value={operation.base} onChange={(value) => update({ base: value })} />
          <NumberRow label="height" value={operation.height} min={1} onChange={(value) => update({ height: value })} />
        </>
      )}
      {operation.type === "cylinder" && (
        <>
          <Vec3Row label="center x/y/z" value={operation.center} onChange={(value) => update({ center: value })} />
          <NumberRow label="radius" value={operation.radius} min={0} onChange={(value) => update({ radius: value })} />
          <NumberRow label="height" value={operation.height} min={1} onChange={(value) => update({ height: value })} />
          <CheckRow label="filled" value={operation.filled} onChange={(value) => update({ filled: value })} />
        </>
      )}
      {operation.type === "sphere" && (
        <>
          <Vec3Row label="center x/y/z" value={operation.center} onChange={(value) => update({ center: value })} />
          <NumberRow label="radius" value={operation.radius} min={0} onChange={(value) => update({ radius: value })} />
          <CheckRow label="filled" value={operation.filled} onChange={(value) => update({ filled: value })} />
        </>
      )}
      {operation.type === "roof_gable" && (
        <>
          <div className="form-row">
            <div className="form-label">axis</div>
            <Dropdown value={operation.axis} options={[{ label: "x", value: "x" }, { label: "z", value: "z" }]} onChange={(value) => update({ axis: value as "x" | "z" })} />
          </div>
          <NumberRow label="overhang" value={operation.overhang} min={0} onChange={(value) => update({ overhang: value })} />
        </>
      )}
      {operation.type === "ring" && (
        <>
          <Vec3Row label="center x/y/z" value={operation.center} onChange={(value) => update({ center: value })} />
          <NumberRow label="radius" value={operation.radius} min={0} onChange={(value) => update({ radius: value })} />
          <NumberRow label="height" value={operation.height} min={1} onChange={(value) => update({ height: value })} />
          <NumberRow label="thickness" value={operation.thickness} min={1} onChange={(value) => update({ thickness: value })} />
        </>
      )}
      {operation.type === "checkerboard_floor" ? (
        <CheckerboardMaterialEditor
          materialA={operation.materialA}
          materialB={operation.materialB}
          onChangeA={(materialA) => update({ materialA })}
          onChangeB={(materialB) => update({ materialB })}
        />
      ) : (
        <MaterialEditor
          block={operation.block}
          material={operation.material}
          allBlocks={allBlocks}
          onBlockChange={(block) => update({ block, material: undefined })}
          onMaterialChange={(material) => update({ material })}
        />
      )}
    </div>
  );
}

function MetadataGroup({ form, updateMetadata }: { form: GenerateFormState; updateMetadata: (key: keyof GenerateFormState["metadata"], value: string | number) => void }) {
  return (
    <div className="group-box">
      <div className="group-box-title">元数据</div>
      <TextRow label="投影名称" value={form.metadata.name} onChange={(value) => updateMetadata("name", value)} />
      <TextRow label="作者" value={form.metadata.author} onChange={(value) => updateMetadata("author", value)} />
      <TextRow label="描述" value={form.metadata.description} onChange={(value) => updateMetadata("description", value)} />
      <NumberRow label="DataVersion" value={form.metadata.minecraftDataVersion} onChange={(value) => updateMetadata("minecraftDataVersion", value)} />
    </div>
  );
}

function RegionGroup({ form, updateRegion }: { form: GenerateFormState; updateRegion: (key: keyof GenerateFormState["region"], value: string | [number, number, number]) => void }) {
  return (
    <div className="group-box">
      <div className="group-box-title">区域设置</div>
      <TextRow label="区域名" value={form.region.name} onChange={(value) => updateRegion("name", value)} />
      <Vec3Row label="origin x/y/z" value={form.region.origin} onChange={(value) => updateRegion("origin", value)} />
      <Vec3Row label="size x/y/z" value={form.region.size} min={1} onChange={(value) => updateRegion("size", value)} />
    </div>
  );
}

function MaterialEditor({
  block,
  material,
  allBlocks,
  onBlockChange,
  onMaterialChange,
}: {
  block: { name: string; properties?: Record<string, string> };
  material?: MaterialSpec;
  allBlocks: string[];
  onBlockChange: (block: { name: string; properties: Record<string, string> }) => void;
  onMaterialChange: (material: MaterialSpec | undefined) => void;
}) {
  const mode = material?.type || "legacy_block";
  const setMode = (nextMode: string) => {
    if (nextMode === "weighted_random") {
      onMaterialChange({
        type: "weighted_random",
        seed: 12345,
        entries: [
          { id: makeId(), weight: 70, block: cloneBlock(block) },
          { id: makeId(), weight: 30, block: { name: "minecraft:cracked_stone_bricks", properties: {} } },
        ],
      });
    } else if (nextMode === "single") {
      onMaterialChange({ type: "single", block: cloneBlock(block) });
    } else {
      onMaterialChange(undefined);
    }
  };
  const singleBlock = material?.type === "single" ? material.block : block;

  return (
    <div className="generate-block-selector">
      <div className="form-row">
        <div className="form-label">材质策略</div>
        <Dropdown
          value={mode}
          options={[
            { label: "旧 block 写法", value: "legacy_block" },
            { label: "material single", value: "single" },
            { label: "weighted random", value: "weighted_random" },
          ]}
          onChange={setMode}
        />
        {allBlocks.length === 0 && <span style={{ opacity: 0.65 }}>BlockState 数据库缺失，保留手动 ID 兜底。</span>}
      </div>
      {mode === "weighted_random" && material?.type === "weighted_random" ? (
        <WeightedRandomEditor material={material} onChange={onMaterialChange} />
      ) : (
        <BlockSelector
          block={singleBlock}
          onChange={(nextBlock) => {
            if (material?.type === "single") onMaterialChange({ type: "single", block: nextBlock });
            else onBlockChange(nextBlock);
          }}
        />
      )}
    </div>
  );
}

function CheckerboardMaterialEditor({
  materialA,
  materialB,
  onChangeA,
  onChangeB,
}: {
  materialA?: MaterialSpec;
  materialB?: MaterialSpec;
  onChangeA: (material: MaterialSpec) => void;
  onChangeB: (material: MaterialSpec) => void;
}) {
  const blockA = materialA?.type === "single" ? materialA.block : { name: "minecraft:white_concrete", properties: {} };
  const blockB = materialB?.type === "single" ? materialB.block : { name: "minecraft:black_concrete", properties: {} };
  return (
    <div className="generate-block-selector">
      <div className="generate-material-entry">
        <div style={{ fontWeight: "bold", marginBottom: 6 }}>棋盘材料 A</div>
        <BlockSelector block={blockA} onChange={(block) => onChangeA({ type: "single", block })} />
      </div>
      <div className="generate-material-entry">
        <div style={{ fontWeight: "bold", marginBottom: 6 }}>棋盘材料 B</div>
        <BlockSelector block={blockB} onChange={(block) => onChangeB({ type: "single", block })} />
      </div>
    </div>
  );
}

function WeightedRandomEditor({ material, onChange }: { material: Extract<MaterialSpec, { type: "weighted_random" }>; onChange: (material: MaterialSpec) => void }) {
  const updateEntry = (index: number, patch: Partial<MaterialEntrySpec>) => {
    onChange({ ...material, entries: material.entries.map((entry, i) => i === index ? { ...entry, ...patch } : entry) });
  };
  const removeEntry = (index: number) => {
    onChange({ ...material, entries: material.entries.filter((_, i) => i !== index) });
  };
  return (
    <div>
      <div className="form-row">
        <div className="form-label">seed</div>
        <input className="input" type="number" value={material.seed} onChange={(e) => onChange({ ...material, seed: Number(e.target.value) })} style={{ width: 160 }} />
        <button className="btn" onClick={() => onChange({ ...material, entries: [...material.entries, { id: makeId(), weight: 10, block: { name: "minecraft:stone_bricks", properties: {} } }] })}>添加 entry</button>
      </div>
      {material.entries.map((entry, index) => (
        <div key={entry.id} className="generate-material-entry">
          <div className="form-row">
            <div className="form-label">weight</div>
            <input className="input" type="number" min={1} value={entry.weight} onChange={(e) => updateEntry(index, { weight: Number(e.target.value) })} style={{ width: 120 }} />
            <button className="btn" onClick={() => removeEntry(index)} disabled={material.entries.length <= 1}>删除</button>
          </div>
          <BlockSelector block={entry.block} onChange={(nextBlock) => updateEntry(index, { block: nextBlock })} />
        </div>
      ))}
    </div>
  );
}

function BlockSelector({ block, onChange }: { block: { name: string; properties?: Record<string, string> }; onChange: (block: { name: string; properties: Record<string, string> }) => void }) {
  const properties = getBlockProperties(block.name);
  const defaultProperties = getDefaultProperties(block.name);
  const propertyKeys = Object.keys(properties).sort();
  const setProperty = (key: string, value: string) => {
    const next = { ...(block.properties || {}) };
    if (!value) delete next[key];
    else next[key] = value;
    onChange({ name: block.name, properties: next });
  };

  return (
    <div>
      <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 8 }}>
        <BlockSearchSelect value={block.name} onChange={(blockId) => onChange({ name: blockId, properties: {} })} />
        <button className="btn" onClick={() => onChange({ name: block.name, properties: { ...defaultProperties } })}>默认状态</button>
        <button className="btn" onClick={() => onChange({ name: block.name, properties: {} })}>清空状态</button>
      </div>
      <details style={{ marginBottom: 8 }}>
        <summary style={{ cursor: "pointer", opacity: 0.75 }}>高级手动 ID</summary>
        <input className="input" value={block.name} onChange={(e) => onChange({ name: e.target.value, properties: {} })} placeholder="minecraft:stone_bricks" style={{ width: "100%", marginTop: 6 }} />
      </details>
      {propertyKeys.length === 0 ? (
        <div style={{ opacity: 0.55, fontSize: "0.9em" }}>无 properties</div>
      ) : (
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          {propertyKeys.map((key) => (
            <label key={key} style={{ display: "flex", alignItems: "center", gap: 4 }}>
              <span>{translateKey(key)}</span>
              <select className="input" value={(block.properties || {})[key] || ""} onChange={(e) => setProperty(key, e.target.value)}>
                <option value="">未指定</option>
                {properties[key].map((value) => <option key={value} value={value}>{translateValue(key, value)} ({value})</option>)}
              </select>
            </label>
          ))}
        </div>
      )}
    </div>
  );
}

function SummaryView({ summary }: { summary: GenerateSummary }) {
  return (
    <div className="generate-summary">
      <div>regions count: {summary.regions_count}</div>
      <div>operation count: {summary.operation_count ?? "-"}</div>
      <div>total volume: {summary.total_volume}</div>
      <div>estimated non-air blocks: {summary.estimated_non_air_blocks}</div>
      <div>estimated palette count: {summary.estimated_palette_count ?? "-"}</div>
      <div>palette entries: {summary.palette_entries_per_region.map((entry) => `${entry.region}=${entry.palette_entries}`).join(", ")}</div>
      <div style={{ marginTop: 6, fontWeight: "bold" }}>material summary</div>
      {summary.material_summary.map((entry) => (
        <div key={`${entry.block_id}-${JSON.stringify(entry.properties)}`}>{entry.block_id} {Object.keys(entry.properties).length ? JSON.stringify(entry.properties) : "{}"} : {entry.count}</div>
      ))}
      {summary.operations && summary.operations.length > 0 && (
        <>
          <div style={{ marginTop: 6, fontWeight: "bold" }}>operations</div>
          {summary.operations.map((operation) => (
            <div key={`${operation.region}-${operation.index}`}>#{operation.index + 1} {operation.name || operation.operation_type}: {operation.affected_block_count}</div>
          ))}
        </>
      )}
      {summary.warnings.length > 0 && <div style={{ color: "#ffd580" }}>warnings: {summary.warnings.join("; ")}</div>}
    </div>
  );
}

function ErrorList({ errors }: { errors: string[] }) {
  return <div className="generate-error-list">{errors.map((error) => <div key={error}>{error}</div>)}</div>;
}

function TextRow({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return (
    <div className="form-row">
      <div className="form-label">{label}</div>
      <input className="input" style={{ flex: 1 }} value={value} onChange={(e) => onChange(e.target.value)} />
    </div>
  );
}

function NumberRow({ label, value, onChange, min }: { label: string; value: number; onChange: (value: number) => void; min?: number }) {
  return (
    <div className="form-row">
      <div className="form-label">{label}</div>
      <input className="input" type="number" min={min} value={value} onChange={(e) => onChange(Number(e.target.value))} style={{ width: 120 }} />
    </div>
  );
}

function CheckRow({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) {
  return (
    <div className="form-row">
      <div className="form-label">{label}</div>
      <label style={{ display: "flex", gap: 6, alignItems: "center" }}>
        <input type="checkbox" checked={value} onChange={(e) => onChange(e.target.checked)} />
        true
      </label>
    </div>
  );
}

function Vec3Row({ label, value, onChange, min }: { label: string; value: [number, number, number]; onChange: (value: [number, number, number]) => void; min?: number }) {
  const setAxis = (axis: 0 | 1 | 2, next: number) => {
    const vec: [number, number, number] = [...value] as [number, number, number];
    vec[axis] = next;
    onChange(vec);
  };
  return (
    <div className="form-row">
      <div className="form-label">{label}</div>
      {[0, 1, 2].map((axis) => (
        <input key={axis} className="input" type="number" min={min} value={value[axis]} onChange={(e) => setAxis(axis as 0 | 1 | 2, Number(e.target.value))} style={{ width: 82, marginRight: 6 }} />
      ))}
    </div>
  );
}


